"""add_description_to_assignments

Revision ID: 4de4fdb067c3
Revises: b73c4d5e6f10
Create Date: 2026-10-05 22:41:36.429993
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4de4fdb067c3'
down_revision: str | None = 'b73c4d5e6f10'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'description')
    # ### end Alembic commands ###
