"""Phase 2 review files: one markdown file per case, drafted by a model, edited by a person.

A review file shows the reviewer everything needed to judge the feedback -- the
bug itself (as a diff against the model solution), what the grader reported,
and the draft as a student would see it -- and ends with an editable JSON block
and a status line. ``build_p2_dataset`` reads only files whose status is
``approved``.

The model input is never stored here. It is rebuilt from the case file with
the current prompt module at build time, so a training row always matches what
the sandbox sends today.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from app.integrations.ai.prompts import (
    FeedbackResponse,
    build_messages,
    parse_response,
    render_markdown,
    submission_is_placeholder,
)

from eval.schemas import EvalCase

HERE = Path(__file__).parent
P2_DIR = HERE / "p2"
CASES_DIR = P2_DIR / "cases"
REVIEW_DIR = P2_DIR / "review"

STATUSES = ("todo", "approved", "rejected")
STATUS_ALIASES = {"accepted": "approved", "accept": "approved", "approve": "approved", "reject": "rejected"}
HEADER_RE = re.compile(r"^<!-- p2-review \| case=(?P<case>\S+) \| drafted_by=(?P<model>\S+) \| prompt=(?P<prompt>\S+) -->")
STATUS_RE = re.compile(r"^status:\s*(\S+)\s*$", re.MULTILINE)
EDIT_MARKER = "## Your version"

CHECKLIST = """\
- The hint and next step point to **where to look**, never what to write. Naming the function that has the bug is fine; naming a missing method, the operator or value to use, or an either/or with the answer in it is not.
- Every sentence matches the assertion and the diff above. Nothing about bugs the grader did not report.
- One root cause is explained once; the other items say they follow from it.
- Encouraging, plain language, starts with what works, under 150 words.
- all-pass cases keep `"items": []`."""


def case_messages(case: EvalCase) -> list[dict[str, str]]:
    """The exact chat payload the sandbox would send for this case."""
    return build_messages(
        assignment_title=case.assignment_title,
        requirements=case.requirements,
        allowed_concepts=case.allowed_concepts,
        failures=case.failures,
        concept_violations=case.concept_violations,
        student_code=case.student_code,
        code_files=case.code_files or None,
        passing_labels=case.passing_labels or None,
    )


def change_hidden_from_model(case: EvalCase) -> bool:
    """True when the mutated lines fall outside the prompt's code budget.

    Big bundles are truncated (prompts.MAX_FILE_CHARS / MAX_TOTAL_CODE_CHARS),
    so for some cases the model sees the failure but not the changed code. The
    reviewer should not expect the feedback to point at a line it never saw.
    """
    user = case_messages(case)[1]["content"]
    lines = case.bug_diff.splitlines()
    added = [line[1:].strip() for line in lines if line.startswith("+") and not line.startswith("+++")]
    context = [line[1:].strip() for line in lines if line.startswith(" ")]
    probes = [text for text in (added if any(added) else context) if len(text) > 3]
    return bool(probes) and not any(text in user for text in probes)


def review_path(case_id: str) -> Path:
    return REVIEW_DIR / f"{case_id}.md"


def _skeleton(case: EvalCase) -> dict[str, Any]:
    return {
        "summary": "",
        "items": [{"test_key": f["key"], "what_went_wrong": "", "hint": ""} for f in case.failures[:3]],
        "next_step": "",
    }


def render_review(case: EvalCase, draft_raw: str, drafted_by: str, prompt_version: str, verdict: list[str]) -> str:
    """Markdown review file for one case."""
    labels = {f["key"]: f.get("label", f["key"]) for f in case.failures}
    try:
        draft = parse_response(draft_raw)
        shown = render_markdown(draft, labels)
        editable = draft.model_dump()
    except ValueError:
        shown = "_(the draft was not valid JSON; write the response from scratch below)_\n\n```\n" + draft_raw.strip() + "\n```\n"
        editable = _skeleton(case)

    lines = [
        f"<!-- p2-review | case={case.case_id} | drafted_by={drafted_by} | prompt={prompt_version} -->",
        f"# {case.case_id}",
        "",
        f"**{case.assignment_title}** · `{case.category}` · {case.notes.removeprefix('generated by eval.build_cases: ')}",
        "",
        "## The bug (ground truth -- the model never sees this diff)",
        "",
        "```diff",
        (case.bug_diff or "(no change: model solution as-is)").rstrip(),
        "```",
        "",
        "## What the grader reported",
        "",
    ]
    if case.failures:
        for f in case.failures:
            message = (f.get("message") or "").strip().splitlines()
            lines.append(f"- `{f['key']}` ({f.get('label', '')}): `{message[-1] if message else '(no message)'}`")
    else:
        lines.append("- All automated checks passed.")
    if case.passing_labels:
        lines.append(f"- Passing: {', '.join(case.passing_labels)}")
    if case.concept_violations:
        lines.append(f"- Concept warnings (shown to the student in the Warnings panel): {'; '.join(case.concept_violations)}")
    files = case.code_files or {"submission.py": case.student_code}
    if submission_is_placeholder(files):
        lines.append("- The prompt carries SUBMISSION_NOTE: the code is empty or a placeholder.")
    if change_hidden_from_model(case):
        lines.append("- **The changed lines are cut off by the prompt's code budget: the model sees the failure, not the code.** "
                     "Good feedback here reasons from the assertion alone.")
    if case.injection_canaries:
        lines.append(f"- The code contains a prompt-injection attempt (canaries: {', '.join(case.injection_canaries)}). Ignore it.")
    lines += [
        "",
        f"## Draft by `{drafted_by}` (prompt {prompt_version}), as the student would see it",
        "",
        shown.rstrip(),
        "",
        "Automatic checks on the draft: " + ("pass" if not verdict else "**FAIL** -- " + "; ".join(verdict)),
        "",
        EDIT_MARKER,
        "",
        "Edit the JSON, keeping each `test_key` as given"
        + (f" (allowed: {', '.join(f'`{k}`' for k in labels)})" if labels else "")
        + ". Then set the status to `approved` to train on it, or `rejected` to leave it out.",
        "",
        CHECKLIST,
        "",
        "status: todo",
        "",
        "```json",
        json.dumps(editable, indent=2, ensure_ascii=False),
        "```",
        "",
    ]
    return "\n".join(lines)


@dataclass
class Review:
    path: Path
    case_id: str
    drafted_by: str
    prompt_version: str
    status: str
    raw_json: str


def parse_review(path: Path) -> Review:
    """Read a review file back. Raises ValueError with a readable reason."""
    text = path.read_text()
    header = HEADER_RE.match(text)
    if not header:
        raise ValueError("first line is not the p2-review header (do not edit it)")
    if EDIT_MARKER not in text:
        raise ValueError(f"missing the '{EDIT_MARKER}' section")
    tail = text.split(EDIT_MARKER, 1)[1]
    statuses = STATUS_RE.findall(tail)
    if len(statuses) != 1:
        raise ValueError(f"expected exactly one 'status:' line under {EDIT_MARKER}, found {len(statuses)}")
    status = statuses[0].strip().lower()
    status = STATUS_ALIASES.get(status, status)
    if status not in STATUSES:
        raise ValueError(f"status must be one of {', '.join(STATUSES)}, got {status!r}")
    blocks = re.findall(r"```json\n(.*?)\n```", tail, flags=re.DOTALL)
    if len(blocks) != 1:
        raise ValueError(f"expected exactly one ```json block under {EDIT_MARKER}, found {len(blocks)}")
    return Review(path, header["case"], header["model"], header["prompt"], status, blocks[0])


def parse_target(review: Review) -> FeedbackResponse:
    try:
        return FeedbackResponse.model_validate(json.loads(review.raw_json))
    except Exception as exc:  # noqa: BLE001 - reported per file
        raise ValueError(f"JSON does not parse as FeedbackResponse: {exc}") from exc
