#!/usr/bin/env python3
"""Mock a student's sandbox run end to end, with synthetic code only.

    python3 scripts/mock_sandbox_run.py --list
    python3 scripts/mock_sandbox_run.py CASE_ID --api http://10.115.20.200/api
    python3 scripts/mock_sandbox_run.py CASE_ID --save-zip ~/Desktop/mock.zip

Takes an eval case (a deliberately broken copy of an instructor's model
solution, from backend/eval/cases.jsonl), zips it the way a student would
submit it, uploads it to the sandbox exactly as the browser does, waits for the
grader, asks for AI feedback, and prints what the student would see next to
what the bug really is. No login and no student data: the code is synthetic.

--save-zip writes the bundle instead, to upload by hand in the sandbox page.
--api defaults to the backend on the Dell itself (http://127.0.0.1:8000); from
another machine use the reverse proxy, http://<host>/api.

Standard library only, so it runs anywhere python3 does.
"""

from __future__ import annotations

import argparse
import io
import json
import sys
import time
import urllib.error
import urllib.request
import uuid
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CASES = REPO / "backend" / "eval" / "cases.jsonl"
SEEDS = REPO / "backend" / "app" / "db" / "seeds"
MARK = {"passed": "PASS", "failed": "FAIL", "warning": "WARN", "not_run": "----"}


def the_bug(case: dict) -> str:
    """The changed lines of the mutation, which the model is never shown."""
    lines = [l for l in case.get("bug_diff", "").splitlines()
             if l[:1] in "+-" and l[1:].strip() and not l.startswith(("+++", "---"))]
    note = case.get("notes", "").removeprefix("generated by eval.build_cases:").strip()
    return "\n".join(lines) or note or "(no bug: the model solution, unchanged)"


def load_cases() -> dict[str, dict]:
    cases = [json.loads(line) for line in CASES.read_text().splitlines() if line.strip()]
    # Hand-written cases carry one code blob, not the named files a bundle needs.
    return {c["case_id"]: c for c in cases if c.get("code_files")}


def bundle_for(case: dict) -> bytes:
    """The case's (mutated) Python files plus the seed's other submitted files (images, reflections)."""
    files = dict(case["code_files"])
    config = json.loads((SEEDS / case["assignment_slug"].replace("-", "_") / "config_json.example.json").read_text())
    extra: dict[str, bytes] = {}
    for art in config.get("artifacts", {}).values():
        name = art.get("display_filename")
        if art.get("type") == "model_solution" and name and name not in files:
            path = SEEDS / case["assignment_slug"].replace("-", "_") / name
            if path.is_file():
                extra[name] = path.read_bytes()
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for name, text in files.items():
            archive.writestr(name, text)
        for name, data in extra.items():
            archive.writestr(name, data)
    return buffer.getvalue()


def http(method: str, url: str, *, body: bytes | None = None, headers: dict | None = None, timeout: float = 30):
    request = urllib.request.Request(url, data=body, method=method, headers=headers or {})
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            raw, status, resp_headers = response.read().decode("utf-8", "replace"), response.status, dict(response.headers)
    except urllib.error.HTTPError as exc:
        raw, status, resp_headers = exc.read().decode("utf-8", "replace"), exc.code, dict(exc.headers or {})
    except (urllib.error.URLError, TimeoutError) as exc:
        sys.exit(f"cannot reach {url}: {getattr(exc, 'reason', exc)}")
    try:
        return status, (json.loads(raw) if raw else {}), resp_headers
    except json.JSONDecodeError:
        return status, raw, resp_headers


def find_assignment(api: str, slug: str) -> tuple[str, dict]:
    status, courses, _ = http("GET", f"{api}/sandbox/courses")
    if status != 200 or not isinstance(courses, dict):
        hint = ("the backend errored; see its log (docker logs <backend container>)" if status >= 500
                else "is --api right? From another machine use http://<host>/api")
        sys.exit(f"cannot list sandbox courses at {api} (HTTP {status}: {str(courses)[:200]}). {hint}")
    wanted = {slug, slug.replace("-", "_"), slug.replace("_", "-")}
    seen = []
    for course in courses.get("courses", []):
        _, listing, _ = http("GET", f"{api}/sandbox/courses/{course['id']}/assignments")
        for assignment in (listing or {}).get("assignments", []) if isinstance(listing, dict) else []:
            seen.append(assignment["id"])
            if assignment["id"] in wanted:
                return course["id"], assignment
    sys.exit(f"assignment '{slug}' is not sandbox-enabled on this server. Available: {', '.join(sorted(seen)) or 'none'}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("case", nargs="?", help="eval case id (see --list)")
    parser.add_argument("--list", action="store_true", help="list the cases you can submit")
    parser.add_argument("--api", default="http://127.0.0.1:8000", help="backend base URL (from another machine: http://<host>/api)")
    parser.add_argument("--save-zip", type=Path, help="write the submission zip here instead of submitting it")
    parser.add_argument("--timeout", type=float, default=180, help="seconds to wait for grading")
    args = parser.parse_args(argv)

    cases = load_cases()
    if args.list or not args.case:
        print(f"{'case':42} {'assignment':24} {'kind':18} bug")
        for c in sorted(cases.values(), key=lambda c: (c["assignment_slug"], c["case_id"])):
            first = the_bug(c).splitlines()[0].strip()
            print(f"{c['case_id']:42} {c['assignment_slug']:24} {c['category']:18} {first[:70]}")
        return 0 if args.list else 2
    case = cases.get(args.case) or sys.exit(f"no case '{args.case}' (see --list)")
    bundle = bundle_for(case)
    bug = the_bug(case)

    if args.save_zip:
        path = args.save_zip.expanduser()
        path.write_bytes(bundle)
        print(f"wrote {path} ({len(bundle)} bytes) for '{case['assignment_title']}'.\nThe bug:\n{bug}")
        return 0

    api = args.api.rstrip("/")
    course_id, assignment = find_assignment(api, case["assignment_slug"])
    print(f"{case['assignment_title']}  ·  case {case['case_id']}")
    print(f"The bug (the model is not told this):\n{bug}\n")

    boundary = f"----mock{uuid.uuid4().hex}"
    body = (f"--{boundary}\r\nContent-Disposition: form-data; name=\"bundle\"; filename=\"submission.zip\"\r\n"
            f"Content-Type: application/zip\r\n\r\n").encode() + bundle + f"\r\n--{boundary}--\r\n".encode()
    status, created, headers = http("POST", f"{api}/sandbox/courses/{course_id}/assignments/{assignment['id']}/runs",
                                    body=body, headers={"Content-Type": f"multipart/form-data; boundary={boundary}"})
    if status != 202 or not isinstance(created, dict):
        sys.exit(f"upload rejected: HTTP {status} {str(created)[:300]}")
    session = headers.get("X-Sandbox-Session") or headers.get("x-sandbox-session") or created.get("sandbox_session") or ""
    run_id = created["run_id"]

    started, result = time.time(), None
    while time.time() - started < args.timeout:
        status, result, _ = http("GET", f"{api}{created['result_url']}", headers={"X-Sandbox-Session": session})
        if status == 200:
            break
        if status != 409:  # 409 = still grading
            sys.exit(f"could not fetch the result: HTTP {status} {str(result)[:300]}")
        time.sleep(2)
    else:
        sys.exit(f"grading did not finish within {args.timeout:.0f}s (run {run_id})")
    print(f"Grader ({time.time() - started:.0f}s): {result['projected_score']}/{result['max_score']}, state {result['state']}")
    for test in result.get("test_summaries", []):
        print(f"  {MARK.get(test['status'], test['status']):4}  {test['label']}  ({test['points_awarded']}/{test['points_possible']})")
    for warning in result.get("warnings", []):
        print(f"  WARN  {warning['code']}: {warning['message']}")

    started = time.time()
    status, feedback, _ = http("POST", f"{api}/sandbox/runs/{run_id}/ai-feedback",
                               headers={"X-Sandbox-Session": session}, timeout=180)
    if status != 200 or not isinstance(feedback, dict):
        sys.exit(f"\nAI feedback request failed: HTTP {status} {str(feedback)[:300]}")
    print(f"\nAI feedback ({time.time() - started:.1f}s, model {feedback.get('model')}):\n")
    print("  " + feedback["ai_feedback"].strip().replace("\n", "\n  "))
    if feedback["ai_feedback"].startswith("\u26a0") or "couldn't produce hints" in feedback["ai_feedback"]:
        print("\n(A fallback message: the model was unreachable, timed out, or its answer failed the safety checks. On the Dell:\n"
              " systemctl status vllm-cs1410, and check the backend's LOCAL_LLM_ENDPOINT / LOCAL_LLM_MODEL.)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
